# create github action to authenticate with google cloud and deploy the terraform code
name: CI    
on:
  push:
    branches:
      - main
jobs:
    terraform:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout code
          uses: actions/checkout@v4
        # setup google cloud sdk
        - id: 'auth'
          uses: 'google-github-actions/auth@v2'
          with:
            credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}
        - name: 'Set up Cloud SDK'
          uses: 'google-github-actions/setup-gcloud@v2'
        - name: Setup Terraform
          uses: hashicorp/setup-terraform@v1
          with:
            terraform_version: 1.0.0
        - name: Terraform Init
          run: terraform init
        - name: Terraform Apply
          run: terraform apply -auto-approve
        